name: Bug Report
description: Report a defect or unexpected behavior in the GitHub Copilot SDK
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please provide as much detail as possible.

  - type: dropdown
    id: sdk
    attributes:
      label: SDK
      description: Which SDK are you using?
      options:
        - Node.js / TypeScript
        - Python
        - Go
        - .NET
        - Multiple / All
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the SDK are you using?
      placeholder: "e.g. 1.2.3"
    validations:
      required: true

  - type: input
    id: cli-version
    attributes:
      label: Copilot CLI Version
      description: What version of the Copilot CLI are you using? (Run `copilot --version`)
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Create a CopilotClient with options '...'
        2. Call session.sendAndWait with prompt '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages or stack traces.
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: A minimal, self-contained code snippet that reproduces the issue.
      render: typescript

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the problem here.
