name: Feature Request
description: Suggest a new feature or enhancement for the GitHub Copilot SDK
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Before submitting, please check existing issues to avoid duplicates.

  - type: dropdown
    id: sdk
    attributes:
      label: Affected SDK(s)
      description: Which SDK(s) should this feature apply to?
      multiple: true
      options:
        - Node.js / TypeScript
        - Python
        - Go
        - .NET
        - All SDKs
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you are experiencing. What are you trying to do that is currently not possible or difficult?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you would like to see added. How would it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any workarounds or alternative solutions you have considered.

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show what the feature would look like in code.
      render: typescript

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low — nice to have
        - Medium — would significantly improve my workflow
        - High — blocking my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, links, or references that may help.
